### ISSUE TITLE
Styles are being evaluated multiple times

### ISSUE THREAD

**Issue by billdwhite** [atoha/dbootstrap#34] opened 2013-04-01 19:38 UTC
I'm seeing the same styles being evaluated by Chrome (and all other browsers I would assume) when I look at the style inheritance for anything I theme with dbootstrap.  I tested this by looking the styles applied to your online demo and the same issue appears there too. Basically it appears that it runs through the same CSS class declarations multiple times. (see attached screenshot). I would assume this is because the .CSS is being loaded or referenced in different places.  I suspect if you run the demo with a link tage referencing the .css file, this problem would go away, but then you'd have the issue you mentioned in the release notes with icon loading.  Still, I would think multiple evaluations of the same CSS classes would lead to a performance hit, but I could be wrong.  
![CSSEvaluationIssue](https://f.cloud.github.com/assets/233476/325235/a501082e-9b03-11e2-8f35-2d890acceb7b.png)

**Comment by martinpengellyphillips** [comment] 2013-04-02 16:22
Good call. I was bundling the css load with the javascript under the impression it might make things easier for those using the system, but it does lead to this issue (as well as reduce control of css ordering if you want to override things)! I'll move it out and update the docs to explain that you have to include the generated css stylesheet manually and hopefully that will, as you say, make this issue go away as well.

**Comment by billdwhite** [comment] 2013-04-02 23:53
Investigating this issue further ( _I am using dbootstrap on a project and this is a show-stopper for me at the moment_ ), I found that if I just run a simple build, the resulting **dbootstrap.css** file contains duplicate class definitions.  

For example, just run a simple build using the "./build.py -v debug theme" command and then search the resulting dbootstrap.css file for this:

**.dbootstrap .dijitButtonNode {border: none;}**

and you will find it included 4 different times.  Likewise, you find it 4 times in the [dbootstrap.css](http://thesociable.github.com/dbootstrap/dbootstrap/theme/dbootstrap/dbootstrap.css) used in your online demo.

So I am thinking the issue is actually with the build process which is writing a lot of duplicate code into the generated css file.  Is that what you were referring to when you said you were "bundling the css load with the javascript"?  I was not sure what that meant.

Thanks

**Comment by martinpengellyphillips** [comment] 2013-04-04 23:59
Ah - I see what you mean now. Ignore my previous comment as it is related to a different issue.

The duplicate entries seem to be down to left-over import statements. For example, Common imports Button creating duplicate Button entries in the output. I'll take a look at cleaning up all the import statements to reduce duplicates.

**Comment by martinpengellyphillips** [comment] 2013-04-05 12:08
Please try out branch 34_duplicate_style_rules and let me know if it solves the issue for you (then I'll merge to master).

**Comment by billdwhite** [comment] 2013-04-05 15:59
Excellent.  I did a build using the 34_duplicate_style_rules branch and it appears to have removed the duplicates.  Please feel free to merge into master.  Once that's done I'll check out the master and verify that it is still working.  Thanks for the quick fix.

**Comment by martinpengellyphillips** [comment] 2013-04-05 16:07
Thanks for checking - have now merged to master. Check it out and let me know if this issue is good to close.

**Comment by billdwhite** [comment] 2013-04-06 02:01
I did a build from master and the css seems fixed.  I do get an error now during my build's layering process because it complains that icon_support.js and package.js are not found; I fixed it by manually copying them over to the build folder where the layering is taking place.  Did you modify how those files get used during the build.py execution? If you find nothing similar on your end, then I think we can consider this bug closed and we will assume the build issue is something on my end. Thanks again for the quick turn around.

**Comment by martinpengellyphillips** [comment] 2013-04-06 12:29
Nothing should have changed with those files. I did a quick test here (building on Ubuntu) and it seems fine so will close this for now. Please feel free to raise a new issue for your build if you discover the problem is in dbootstrap.

**Closed as completed by martinpengellyphillips** 2013-04-06 12:29 UTC
